const data = [
  {
    category: "Apparel",
    id: "1",
    title: "Apparel 1",
    price: "120",
    img: "Rectangle325.png",
  },
  {
    category: "Apparel",
    id: "2",
    title: "Apparel 2",
    price: "100",
    img: "Rectangle325.png",
  },
  {
    category: "Apparel",
    id: "3",
    title: "Apparel 3",
    price: "150",
    img: "Rectangle325.png",
  },
  {
    category: "Apparel",
    id: "4",
    title: "Apparel 4",
    price: "40",
    img: "Rectangle325.png",
  },
  {
    category: "Dress",
    id: "5",
    title: "Dress 1",
    price: "120",
    img: "Rectangle325(2).png",
  },
  {
    category: "Dress",
    id: "6",
    title: "Dress 2",
    price: "100",
    img: "Rectangle325(2).png",
  },
  {
    category: "Dress",
    id: "7",
    title: "Dress 3",
    price: "150",
    img: "Rectangle325(2).png",
  },
  {
    category: "Dress",
    id: "8",
    title: "Dress 4",
    price: "40",
    img: "Rectangle325(2).png",
  },
  {
    category: "Tshirt",
    id: "9",
    title: "Tshirt 1",
    price: "120",
    img: "Rectangle325(3).png",
  },
  {
    category: "Tshirt",
    id: "10",
    title: "Tshirt 2",
    price: "100",
    img: "Rectangle325(3).png",
  },
  {
    category: "Tshirt",
    id: "11",
    title: "Tshirt 3",
    price: "150",
    img: "Rectangle325(3).png",
  },
  {
    category: "Tshirt",
    id: "12",
    title: "Tshirt 4",
    price: "40",
    img: "Rectangle325(3).png",
  },
  {
    category: "Bag",
    id: "13",
    title: "Bag 1",
    price: "120",
    img: "Rectangle325(4).png",
  },
  {
    category: "Bag",
    id: "14",
    title: "Bag 2",
    price: "100",
    img: "Rectangle325(4).png",
  },
  {
    category: "Bag",
    id: "15",
    title: "Bag 3",
    price: "150",
    img: "Rectangle325(4).png",
  },
  {
    category: "Bag",
    id: "16",
    title: "Bag 4",
    price: "40",
    img: "Rectangle325(4).png",
  },
];

export default data;
