const data = [
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 1,
    title: "Apparel 1",
    price: "120",
    rating: "4.3",
    img: "Rectangle325.png",
    color: ["#000", "#FFF", "#DD8560"],
  },
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 2,
    title: "Apparel 2",
    price: "100",
    rating: "4.3",
    img: "Rectangle325.png",
  },
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 3,
    title: "Apparel 3",
    price: "150",
    rating: "4.3",
    img: "Rectangle325.png",
  },
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 4,
    title: "Apparel 4",
    price: "40",
    rating: "4.3",
    img: "Rectangle325.png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 5,
    title: "Dress 1",
    price: "120",
    rating: "4.3",
    img: "Rectangle325(2).png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 6,
    title: "Dress 2",
    price: "100",
    rating: "4.3",
    img: "Rectangle325(2).png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 7,
    title: "Dress 3",
    price: "150",
    rating: "4.3",
    img: "Rectangle325(2).png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 8,
    title: "Dress 4",
    price: "40",
    rating: "4.3",
    img: "Rectangle325(2).png",
  },
  {
    category: "Tshirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 9,
    title: "Tshirt 1",
    price: "120",
    rating: "4.3",
    img: "Rectangle325(3).png",
  },
  {
    category: "Tshirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 10,
    title: "Tshirt 2",
    price: "100",
    rating: "4.3",
    img: "Rectangle325(3).png",
  },
  {
    category: "Tshirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 11,
    title: "Tshirt 3",
    price: "150",
    rating: "4.3",
    img: "Rectangle325(3).png",
  },
  {
    category: "Tshirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 12,
    title: "Tshirt 4",
    price: "40",
    rating: "4.3",
    img: "Rectangle325(3).png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 13,
    title: "Bag 1",
    price: "120",
    rating: "4.3",
    img: "Rectangle325(4).png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 14,
    title: "Bag 2",
    price: "100",
    rating: "4.3",
    img: "Rectangle325(4).png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 15,
    title: "Bag 3",
    price: "150",
    rating: "4.3",
    img: "Rectangle325(4).png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 16,
    title: "Bag 4",
    price: "40",
    rating: "4.3",
    img: "Rectangle325(4).png",
  },
];

export default data;
