const data = [
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 1,
    title: "Apparel 1",
    price: 120,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Apparel1.png",
  },
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 2,
    title: "Apparel 2",
    price: 100,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Apparel2.png",
  },
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 3,
    title: "Apparel 3",
    price: 150,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Apparel3.png",
  },
  {
    category: "Apparel",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 4,
    title: "Apparel 4",
    price: 40,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Apparel4.png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 5,
    title: "Dress 1",
    price: 120,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Dress1.png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 6,
    title: "Dress 2",
    price: 100,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Dress2.png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 7,
    title: "Dress 3",
    price: 150,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Dress3.png",
  },
  {
    category: "Dress",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 8,
    title: "Dress 4",
    price: 40,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Dress4.png",
  },
  {
    category: "Shirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 9,
    title: "Shirt 1",
    price: 120,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Shirt1.png",
  },
  {
    category: "Shirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 10,
    title: "Shirt 2",
    price: 100,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Shirt2.png",
  },
  {
    category: "Shirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 11,
    title: "Shirt 3",
    price: 150,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Shirt3.png",
  },
  {
    category: "Shirt",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 12,
    title: "Shirt 4",
    price: 40,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Shirt4.png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 13,
    title: "Bag 1",
    price: 120,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Bag1.png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 14,
    title: "Bag 2",
    price: 100,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Bag2.png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 15,
    title: "Bag 3",
    price: 150,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Bag3.png",
  },
  {
    category: "Bag",
    description: "Recycle Boucle Knit Cardigan Pink",
    id: 16,
    title: "Bag 4",
    price: 40,
    rating: 4.3,
    color: ["#000", "#DD8560", "#E1E0DB"],
    size: ["SM", "L", "XL", "2XL"],
    img: "Bag4.png",
  },
];

function getProductData(id) {
  let productData = data.find((item) => item.id === id);

  return productData;
}

export { data, getProductData };
